# Generated by Django 4.2.2 on 2023-06-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_created_at_alter_article_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
    ]
