# Generated by Django 4.2.2 on 2023-07-05 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_article_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="reporters",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="comment",
            name="reports",
            field=models.IntegerField(default=0),
        ),
    ]
